spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimeZone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
