spring:
  datasource:
    url: jdbc:mysql://boqipaa9p571zrjqmie6-mysql.services.clever-cloud.com:3306/boqipaa9p571zrjqmie6?useSSL=false&serverTimeZone=UTC
    username: ulghiwshmslbldlh
    password: z5LpX1iumM2uAjtczICI
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
